// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class Intersection {
	/**
	 * 
	 */
	private Long longitude;
	/**
	 * 
	 */
	private Long latitude;
	/**
	 * 
	 */
	private String nom;
};
