// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

/************************************************************/
/**
 * 
 */
public class Requete {

	/**  
	 * 
	 */
	private Intersection pointDeRecuperation;
	/**
	 * 
	 */
	private Intersection pointDeLivraison;
	/**
	 * 
	 */
	private Long dureeRecuperation;
	/**
	 * 
	 */
	private Long dureeLivraison;
	
	
	
	
	/* Method */
	public Requete(Intersection pointDeRecuperation, Intersection pointDeLivraison, Long dureeRecuperation,
			Long dureeLivraison) {
		super();
		this.pointDeRecuperation = pointDeRecuperation;
		this.pointDeLivraison = pointDeLivraison;
		this.dureeRecuperation = dureeRecuperation;
		this.dureeLivraison = dureeLivraison;
	}
	public Requete() {
		super();
	}
	public Intersection getPointDeRecuperation() {
		return pointDeRecuperation;
	}
	public void setPointDeRecuperation(Intersection pointDeRecuperation) {
		this.pointDeRecuperation = pointDeRecuperation;
	}
	public Intersection getPointDeLivraison() {
		return pointDeLivraison;
	}
	public void setPointDeLivraison(Intersection pointDeLivraison) {
		this.pointDeLivraison = pointDeLivraison;
	}
	public Long getDureeRecuperation() {
		return dureeRecuperation;
	}
	public void setDureeRecuperation(Long dureeRecuperation) {
		this.dureeRecuperation = dureeRecuperation;
	}
	public Long getDureeLivraison() {
		return dureeLivraison;
	}
	public void setDureeLivraison(Long dureeLivraison) {
		this.dureeLivraison = dureeLivraison;
	}
	
	@Override
	public String toString() {
		return "Requete [pointDeRecuperation=" + pointDeRecuperation + ", pointDeLivraison=" + pointDeLivraison
				+ ", dureeRecuperation=" + dureeRecuperation + ", dureeLivraison=" + dureeLivraison + "]";
	}
	

	
	
};
