// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

import modele.Intersection;

/************************************************************/
/**
 * 
 */
public class Requete {
	/**
	 * 
	 */
	public Intersection pointDeRecuperation;
	/**
	 * 
	 */
	public Intersection pointDeLivraison;
};
