// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modele;

import modele.Intersection;

/************************************************************/
/**
 * 
 */
public class Segment {
	/**
	 * 
	 */
	public Intersection origine;
	/**
	 * 
	 */
	public Intersection fin;
	/**
	 * 
	 */
	private int longueur;
	/**
	 * 
	 */
	private String nom;
};
